# Author: ANJOU Raphaël
# Company: Orange Business
# Year: 2023
# Project: Traefik Demo

version: '3.9'

networks:
  traefik-net:
    external: true

services:
  whoami-replicate:
    # Warning : do not use 'container-name' because replicas can't handle a custom name
    # Or at least I've not found yet how to do it
    # container-name: DO-NOT
    image: traefik/whoami:latest
    ports:
      - "8000-8002:80"
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.services.whoami-replicate.loadbalancer.server.port=80
      - traefik.http.routers.whoami-replicate.rule=Host(`replicas.localhost`)
    deploy:
      replicas: 3
